#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

#-------------------------------------------------------------------------------
# General
#-------------------------------------------------------------------------------

# Set computer name (as done via System Preferences → Sharing)
sudo scutil --set ComputerName msola-workstation

# Automatically quit printer app once the print jobs complete
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

#-------------------------------------------------------------------------------
# Transmission
#-------------------------------------------------------------------------------

# Don’t prompt for confirmation before downloading
defaults write org.m0k.transmission DownloadAsk -bool false

# Trash original torrent files
defaults write org.m0k.transmission DeleteOriginalTorrent -bool true

# Hide the donate message
defaults write org.m0k.transmission WarningDonate -bool false
# Hide the legal disclaimer
defaults write org.m0k.transmission WarningLegal -bool false
