#!/usr/bin/env bash

# Install Homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install caskroom/cask/brew-cask

# ------------------------------------------------------------------------------
# System
# ------------------------------------------------------------------------------
brew install git
brew install ag
brew install htop
brew install cmus

# ------------------------------------------------------------------------------
# Node
# ------------------------------------------------------------------------------
brew install node
npm install -g n
n latest
npm install -g gulp
npm install -g cordova
npm install -g browser-sync
npm install -g browserify
npm install -g stylus
npm install -g ionic
npm install -g hexo
npm install -g hexo-server
npm install -g nodemon

# ------------------------------------------------------------------------------
# Apps
# ------------------------------------------------------------------------------
brew cask install google-chrome
brew cask install dropbox
brew cask install transmission
brew cask install skype
brew cask install virtualbox
brew cask install genymotion
brew cask install android-studio
brew cask install smartgit
brew cask install dash
brew cask install slack
brew cask install pandoc
brew cask install basictex
