#!/usr/bin/env bash

# NOTE: We need to have xcode installed.

# ask for the administrator password upfront
sudo -v

# delete previous installation
rm -rf neovim

# install dependencies
xcode-select --install
xcodebuild -license
brew install libtool automake cmake pkg-config gettext

# download sources
git clone https://github.com/neovim/neovim.git

# move to folder
cd neovim

# clean and build
make distclean && make
make install

# remove and copy neovim configuration
rm -rf ~/.config/nvim
mkdir -p ~/.config/nvim
ln -s ~/.dotifles/config.vim ~/.config/nvim/init.vim

# install neovim from repo
#brew tap neovim/homebrew-neovim
#brew install --HEAD neovim

# copy config files
#cp -rf ~/.vim ~/.nvim

#curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
#    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# fix for tmux-neovim ctrl-h bug
infocmp $TERM | sed 's/kbs=^[hH]/kbs=\\177/' > $TERM.ti
tic $TERM.ti
