#! /bin/bash

# Source global definitions
[[ -f /etc/bashrc ]] && . /etc/bashrc

# General
export TERM="screen-256color"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

# ------------------------------------------------------------------------------
# Productivity
# ------------------------------------------------------------------------------

# Program alias
alias vim='nvim'
alias grep='grep --color=auto'
alias tree='tree -L 2 | more'
alias rm='rm -rf'

# Improved navigation
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# Git
alias ga='git add .'
alias gg='git log --oneline --graph --all --decorate'
alias gl='git log --all --decorate'
alias gs='git status'
alias gc='git commit'
alias gd='git diff'
alias gdc='git diff --cached'
alias grh='git reset --hard HEAD'
alias gcm='git checkout master'
alias gcd='git checkout develop'

# ------------------------------------------------------------------------------
# Remote servers
# ------------------------------------------------------------------------------
alias devbox='ssh ionthas@95.85.12.4'
alias bbg='ssh bug@bigbuggames.com'

# ------------------------------------------------------------------------------
# Workflow
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Current working projects
# ------------------------------------------------------------------------------

# Hybreed
alias prep='rm -r www/*; cp -r www-dev/* www/'
alias andr='prep && cordova prepare android && cordova run android'

# ATSistemas
alias at='cd $HOME/repos/atsistemas; ls -lh'

alias mlm='cd $HOME/repos/atsistemas/mlm; ls -lh'
alias m2='cd $HOME/repos/atsistemas/mlm/mlm-back-v2; ls -lh'
alias mu='cd $HOME/repos/atsistemas/mlm/user-case-tests; ls -lh'
alias mh='cd $HOME/repos/atsistemas/mlm/hybreed-cli-mlm-module; ls -lh'

# CaixaBank
alias silk='cd ~/repos/atsistemas/silk/; ls -lh'

# Reset completely the mlm-back-v2 database
alias rdb='gulp reset &; sleep 4 && gulp populate && kill $!'

# Personal
alias gde='cd ~/repos/gamedev; ls -lh'
alias toy='cd ~/repos/toy; ls -lh'

# Notes
alias nn='cd ~/Dropbox/blog/notes; ls -lh'

# ------------------------------------------------------------------------------

source ~/.dotfiles/config/git-prompt.sh 

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
  screen-256color)  color_prompt=yes
esac

if [ "$color_prompt" = yes ]; then
    if [ "$(whoami)" == 'root' ]; then
        PS1='\[\e[33m\]\w $ \[\e[0m\]'
    else
        PS1='\e[1m\w\e[m\e[33m$(__git_ps1)\e[m \[\e[32m\]>\[\e[33m\]>\[\e[31m\]> \[\e[0m\]'
    fi
else
    PS1='\w $ '
fi
unset color_prompt force_color_prompt
