# Adding ssh keys to agent
ssh-add $HOME/.ssh/ionid
ssh-add $HOME/.ssh/msola-at

# Load the default .profile
[[ -s "$HOME/.profile" ]] && source "$HOME/.profile"

# Load default .bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc


