#export JAVA_HOME=$(/usr/libexec/java_home)
#export JAVA_HOME=$JAVA_HOME:$(/usr/libexec/java_home)/bin

export ANDROID_HOME=/Users/ionthas/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

export PATH=$PATH:/usr/local/

#eval "$(docker-machine env default)"

# Load the default .profile
#[[ -s "$HOME/.profile" ]] && source "$HOME/.profile"

# Load default .bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc


