export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="ionthas"

zstyle ':completion:*' insert-tab false

# ------------------------------------------------------------------------------
# Productivity
# ------------------------------------------------------------------------------

# Git
alias gg='git log --oneline --graph --all --decorate'
alias gl='git log --all --decorate'
alias gs='git status'
alias gc='git commit'
alias gd='git diff'
alias gdc='git diff --cached'
alias grh='git reset --hard HEAD'
alias gcm='git checkout master'
alias gcd='git checkout develop'

# ------------------------------------------------------------------------------
# Remote servers
# ------------------------------------------------------------------------------
alias devbox='ssh -i ~/.ssh/ionid ionthas@95.85.12.4'
alias bbg='ssh -i ~/.ssh/ionid bug@bigbuggames.com'

# ------------------------------------------------------------------------------
# Workflow
# ------------------------------------------------------------------------------
alias note='vim ~/Dropbox/documents/notes.md'
alias imp='vim ~/Dropbox/documents/imputaciones.md'

# ------------------------------------------------------------------------------
# Current working projects
# ------------------------------------------------------------------------------

# Hybreed
alias prep='rm -r www/*; cp -r www-dev/* www/'
alias andr='prep && cordova prepare android && cordova run android'

# ATSistemas
alias at='cd $HOME/repos/atsistemas; ls -lh'

alias mlm='cd $HOME/repos/atsistemas/mlm; ls -lh'
alias m2='cd $HOME/repos/atsistemas/mlm/mlm-back-v2; ls -lh'
alias mu='cd $HOME/repos/atsistemas/mlm/user-case-tests; ls -lh'
alias mh='cd $HOME/repos/atsistemas/mlm/hybreed-cli-mlm-module; ls -lh'

alias silk='cd ~/repos/atsistemas/silk; ls -lh'

# Reset completely the mlm-back-v2 database
alias rdb='gulp reset &; sleep 4 && gulp populate && kill $!'

# Personal
alias gde='cd ~/repos/gamedev; ls -lh'
alias ca='cd ~/repos/gamedev/mincaf; ls -lh'

# ------------------------------------------------------------------------------

# setopt rmstarsilent

export PATH=/opt/local/bin:$PATH
export PATH=$PATH:/bin

# # MySQL path
# export PATH=$PATH:/usr/local/mysql/bin

# # Node path
# export NODE_PATH=/usr/local/bin:/usr/local/lib/node_modules

# # Android home
# export ANDROID_HOME=/Users/msola/Library/Android/sdk
# export PATH=$PATH:$ANDROID_HOME/tools
# export PATH=$PATH:$ANDROID_HOME/platform-tools
# export PATH=$PATH:$ANDROID_HOME/build-tools/23.0.1

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

source $ZSH/oh-my-zsh.sh
